<?xml version="1.0" encoding="utf-8"?><Database Name="LinqDB" Class="LinqDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=LinqDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LinqDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserInfo" Member="UserInfo">
    <Type Name="UserInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>